apiVersion: apps/v1
kind: Deployment
metadata:
  name: harborseal-api
  namespace: harborseal
spec:
  template:
    spec:
      containers:
      - name: api
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"