apiVersion: apps/v1
kind: Deployment
metadata:
  name: harborseal-api
  namespace: harborseal-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: DATABASE_NAME
          value: "harborseal-dev"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"