apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: harborseal-api-dev

namespace: harborseal-dev

resources:
- ../../base

namePrefix: dev-

commonLabels:
  environment: development

patchesStrategicMerge:
- api-deployment-patch.yaml

images:
- name: harborseal-api
  newTag: dev