apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: harborseal
spec:
  selector:
    app.kubernetes.io/name: harborseal
    app.kubernetes.io/component: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  clusterIP: None